### ISSUE TITLE
Cannot build on 2021.0

### ISSUE THREAD

**Issue by Warrior555MainsGanon** [Zal0/ZGB#22]
I was on 2020.2 and rom compilation was working fine, but today I installed 2021.0 and compilation doesn't work.
>C:\Users\censored\Downloads\ZGB-template-master\ZGB-template-master>cd src
>
>C:\Users\censored\Downloads\ZGB-template-master\ZGB-template-master\src>C:\Users\censored\Downloads\ZGB->2021.0\ZGB\common\..\env\make-3.81-bin\bin\make run BUILD_TYPE=ReleaseColor
>Linking
>Multiple definition of _empty
>Multiple definition of _empty
>Multiple definition of _empty
>Multiple definition of _empty
>Multiple definition of _empty
>Multiple definition of _empty
>Multiple definition of _empty
>?ASlink-Warning-Cannot open library module ../ReleaseColor/zgb/.rel
>Multiple definition of _empty
>make: *** [../bin/ZgbTest.gbc] Erreur 2
>
>C:\Users\censored\Downloads\ZGB-template-master\ZGB-template-master\src>cd ..
>
>C:\Users\censored\Downloads\ZGB-template-master\ZGB-template-master>pause
>Appuyez sur une touche pour continuer...

Changing back to 2020.2 wasn't helpful since now it makes a new error when compilling:

>
>C:\Users\censored\Downloads\ZGB-template-master\ZGB-template-master>cd src
>
>C:\Users\censored\Downloads\ZGB-template-master\ZGB-template-master\src>C:\Users\censored\Downloads\ZGB-2020.2\ZGB->2020.2\common\..\env\make-3.81-bin\bin\make run BUILD_TYPE=ReleaseColor
>Linking
>C:/Users/censored/Downloads/ZGB-2020.2/ZGB-2020.2/common/../env/gbdk/bin/lcc -Wl-m -Wl-j -Wl-yt1 -Wl-yo128 -Wl->yp0x143=0xC0 -Wl-g.STACK=0xDEFF -k../ReleaseColor/zgb -lzgb.lib -o ../ReleaseColor/ZgbTest.gbc >../ReleaseColor/res/map.b3.gbm.o ../ReleaseColor/res/enemy.b3.gbr.o ../ReleaseColor/res/font.b3.gbr.o >../ReleaseColor/res/player.b3.gbr.o ../ReleaseColor/res/tiles.b3.gbr.o    ../ReleaseColor/SpriteEnemy.o >../ReleaseColor/SpritePlayer.o ../ReleaseColor/StateGame.o ../ReleaseColor/ZGBMain.o
>Error: Format(XL3) Only XL2 format is supported
>Error: Format(XL3) Only XL2 format is supported
>Error: Format(XL3) Only XL2 format is supported
>Error: Format(XL3) Only XL2 format is supported
>Error: Format(XL3) Only XL2 format is supported
>Error: Format(XL3) Only XL2 format is supported
>Error: Format(XL3) Only XL2 format is supported
>Error: Format(XL3) Only XL2 format is supported
>Error: Format(XL3) Only XL2 format is supported
>Error: Format(XL3) Only XL2 format is supported
>Error: Format(XL3) Only XL2 format is supported
>Error: Format(XL3) Only XL2 format is supported
>Error: Format(XL3) Only XL2 format is supported
>Error: Format(XL3) Only XL2 format is supported
>Error: Format(XL3) Only XL2 format is supported
>Error: Format(XL3) Only XL2 format is supported
>Error: Format(XL3) Only XL2 format is supported
>Error: Format(XL3) Only XL2 format is supported
>
>?ASlink-Warning-Undefined Global ___sdcc_bcall_ehl referenced by module Frame
>ERROR: address overflow (addr c0a1 >= 8000)
>c:\Users\censored\Downloads\ZGB-2020.2\ZGB-2020.2\env\gbdk\bin\lcc.exe: c:\Users\censored\Downloads\ZGB-2020.2\ZGB->2020.2\env\gbdk\bin/link-gbz80: No such file or directory
>make: *** [../bin/ZgbTest.gbc] Erreur 1
>
>C:\Users\censored\Downloads\ZGB-template-master\ZGB-template-master\src>cd ..
>
>C:\Users\censored\Downloads\ZGB-template-master\ZGB-template-master>pause
>Appuyez sur une touche pour continuer...

Edit: I deleted the Release/Debug/ReleaseColor/DebugColor folder(s) and compilation with 2020.2 worked again, however 2021.0 still doesn't work

**Comment by Zal0** [comment]
Can you try removing  Release/Debug/ReleaseColor/DebugColor folders and also res/src (that's were I put the compiled resources)?
That should fix it

**Comment by Warrior555MainsGanon** [comment]
Doesn't work for 2021.0, will always give "multiple definition of _empty" and "?ASlink-Warning-Cannot open library module ../ReleaseColor/zgb/.rel"

**Comment by Warrior555MainsGanon** [comment]
Update: Nvm I just forgot res/src

**Comment by Zal0** [comment]
Cool!
I am going to add it on the release notes

**Comment by irishgreencitrus** [comment]
@Zal0 add those folders to a .gitignore

**Comment by Zal0** [comment]
They are already added https://github.com/Zal0/ZGB-template/blob/master/.gitignore#:~:text=%5BDd%5Debug*/,%5BRr%5Deleases/
